# Auto-generated by scripts/generate_spawn_all_npcs_line.sh
# Source directory: /Users/matthewvogt/Dev/Minecraft Modding/playerspawnfixer-template-1.21.1/run/saves/New World/datapacks/pixelmon_research_example/data/safari-zone/pixelmon/npc/preset/areas
# Direction: NORTH (-Z forward)
# Run as player: /function safari-zone:debug/spawn_all_npcs_line


# --- Visitor Center ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-2 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Visitor Center","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/visitor_center/receptionist_gate ~ ~ ~-4
execute as @p at @s run npc spawnlinked safari-zone:areas/visitor_center/receptionist_lobby ~-2 ~ ~-4
execute as @p at @s run npc spawnlinked safari-zone:areas/visitor_center/ticket_clerk ~2 ~ ~-4

# --- Timberland Village ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-10 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Timberland Village","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/frog_maniac_house/frog_maniac ~ ~ ~-12
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_1/basement/dr_petra_stone ~-2 ~ ~-12
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_1/first_floor/dr_keira_holt ~2 ~ ~-12
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_1/second_floor/dr_lyra_quill ~-4 ~ ~-12
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_1/third_floor/rafe_calder ~4 ~ ~-12
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_2/second_floor/selene_vire ~-6 ~ ~-12

# --- Ancient Crater ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-18 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Ancient Crater","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/mru_field_lead ~ ~ ~-20

# --- Mystic Highlands ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-26 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Mystic Highlands","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/mystic_highlands/highlands_lab_contact ~ ~ ~-28

# --- Scorched Mesa ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-34 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Scorched Mesa","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/station_contact ~ ~ ~-36

# --- Twilight Keep ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-42 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Twilight Keep","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/manor_steward ~ ~ ~-44

# --- Neon Grove ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-50 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Neon Grove","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/neon_grove/medical_center_attendant ~ ~ ~-52
