# Auto-generated by scripts/generate_spawn_all_npcs_line.sh
# Source directory: datapacks/pixelmon_research_example/data/safari-zone/pixelmon/npc/preset/areas
# Direction: WEST (-X forward)
# Run as player: /function safari-zone:debug/spawn_all_npcs_line


# --- Visitor Center ---
execute as @p at @s run summon minecraft:armor_stand ~-2 ~2 ~ {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Visitor Center","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/visitor_center/receptionist_gate ~-4 ~ ~
execute as @p at @s positioned ~-4 ~ ~ as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/visitor_center/receptionist_lobby ~-4 ~ ~-2
execute as @p at @s positioned ~-4 ~ ~-2 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/visitor_center/ticket_clerk ~-4 ~ ~2
execute as @p at @s positioned ~-4 ~ ~2 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}

# --- Timberland Village ---
execute as @p at @s run summon minecraft:armor_stand ~-10 ~2 ~ {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Timberland Village","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/frog_maniac_house/frog_maniac ~-12 ~ ~
execute as @p at @s positioned ~-12 ~ ~ as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_1/basement/dr_petra_stone ~-12 ~ ~-2
execute as @p at @s positioned ~-12 ~ ~-2 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_1/first_floor/dr_keira_holt ~-12 ~ ~2
execute as @p at @s positioned ~-12 ~ ~2 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_1/second_floor/dr_lyra_quill ~-12 ~ ~-4
execute as @p at @s positioned ~-12 ~ ~-4 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_1/third_floor/rafe_calder ~-12 ~ ~4
execute as @p at @s positioned ~-12 ~ ~4 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_2/second_floor/selene_vire ~-12 ~ ~-6
execute as @p at @s positioned ~-12 ~ ~-6 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}

# --- Ancient Crater ---
execute as @p at @s run summon minecraft:armor_stand ~-18 ~2 ~ {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Ancient Crater","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/high_hide/eddie ~-20 ~ ~
execute as @p at @s positioned ~-20 ~ ~ as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/lake/submersible/ajay ~-20 ~ ~-2
execute as @p at @s positioned ~-20 ~ ~-2 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/mid/skeleton_structure/roland ~-20 ~ ~2
execute as @p at @s positioned ~-20 ~ ~2 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/mru/ian ~-20 ~ ~-4
execute as @p at @s positioned ~-20 ~ ~-4 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/mru/kelly ~-20 ~ ~4
execute as @p at @s positioned ~-20 ~ ~4 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/mru/nick ~-20 ~ ~-6
execute as @p at @s positioned ~-20 ~ ~-6 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/mru_field_lead ~-20 ~ ~6
execute as @p at @s positioned ~-20 ~ ~6 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/upper/archeops_nest/robert ~-20 ~ ~-8
execute as @p at @s positioned ~-20 ~ ~-8 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}

# --- Mystic Highlands ---
execute as @p at @s run summon minecraft:armor_stand ~-26 ~2 ~ {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Mystic Highlands","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/mystic_highlands/highlands_lab_contact ~-28 ~ ~
execute as @p at @s positioned ~-28 ~ ~ as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}

# --- Scorched Mesa ---
execute as @p at @s run summon minecraft:armor_stand ~-34 ~2 ~ {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Scorched Mesa","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/canyon_observatory/javier ~-36 ~ ~
execute as @p at @s positioned ~-36 ~ ~ as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/dam_control_building/jack ~-36 ~ ~-2
execute as @p at @s positioned ~-36 ~ ~-2 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/mine_camp/marston ~-36 ~ ~2
execute as @p at @s positioned ~-36 ~ ~2 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/oil_fields/cleet ~-36 ~ ~-4
execute as @p at @s positioned ~-36 ~ ~-4 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/ranch/kitty ~-36 ~ ~4
execute as @p at @s positioned ~-36 ~ ~4 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/station_contact ~-36 ~ ~-6
execute as @p at @s positioned ~-36 ~ ~-6 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/train/passenger_cab/leopold ~-36 ~ ~6
execute as @p at @s positioned ~-36 ~ ~6 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/train/rear_cab/abigail ~-36 ~ ~-8
execute as @p at @s positioned ~-36 ~ ~-8 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/train_station/arthur ~-36 ~ ~8
execute as @p at @s positioned ~-36 ~ ~8 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/train_station/bill ~-36 ~ ~-10
execute as @p at @s positioned ~-36 ~ ~-10 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}

# --- Twilight Keep ---
execute as @p at @s run summon minecraft:armor_stand ~-42 ~2 ~ {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Twilight Keep","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/armory/dimitar ~-44 ~ ~
execute as @p at @s positioned ~-44 ~ ~ as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/church_of_tres/priest_mikhail ~-44 ~ ~-2
execute as @p at @s positioned ~-44 ~ ~-2 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/guard_tower/luka ~-44 ~ ~2
execute as @p at @s positioned ~-44 ~ ~2 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/hotel/charles ~-44 ~ ~-4
execute as @p at @s positioned ~-44 ~ ~-4 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/hotel/milan ~-44 ~ ~4
execute as @p at @s positioned ~-44 ~ ~4 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/nikolai ~-44 ~ ~-6
execute as @p at @s positioned ~-44 ~ ~-6 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/observatory/head_scientist_viktor ~-44 ~ ~6
execute as @p at @s positioned ~-44 ~ ~6 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/sorcery_building/elena ~-44 ~ ~-8
execute as @p at @s positioned ~-44 ~ ~-8 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/storage_building/ivan ~-44 ~ ~8
execute as @p at @s positioned ~-44 ~ ~8 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}

# --- Neon Grove ---
execute as @p at @s run summon minecraft:armor_stand ~-50 ~2 ~ {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Neon Grove","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/neon_grove/medical_center_attendant ~-52 ~ ~
execute as @p at @s positioned ~-52 ~ ~ as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
