# Auto-generated by scripts/generate_spawn_all_npcs_line.sh
# Source directory: datapacks/pixelmon_research_example/data/safari-zone/pixelmon/npc/preset/areas
# Direction: NORTH (-Z forward)
# Run as player: /function safari-zone:debug/spawn_all_npcs_line


# --- Visitor Center ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-2 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Visitor Center","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/visitor_center/receptionist_gate ~ ~ ~-4
execute as @p at @s positioned ~ ~ ~-4 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/visitor_center/receptionist_lobby ~-2 ~ ~-4
execute as @p at @s positioned ~-2 ~ ~-4 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/visitor_center/ticket_clerk ~2 ~ ~-4
execute as @p at @s positioned ~2 ~ ~-4 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}

# --- Timberland Village ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-10 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Timberland Village","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/frog_maniac_house/frog_maniac ~ ~ ~-12
execute as @p at @s positioned ~ ~ ~-12 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_1/basement/dr_petra_stone ~-2 ~ ~-12
execute as @p at @s positioned ~-2 ~ ~-12 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_1/first_floor/dr_keira_holt ~2 ~ ~-12
execute as @p at @s positioned ~2 ~ ~-12 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_1/second_floor/dr_lyra_quill ~-4 ~ ~-12
execute as @p at @s positioned ~-4 ~ ~-12 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_1/third_floor/rafe_calder ~4 ~ ~-12
execute as @p at @s positioned ~4 ~ ~-12 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/timberland_village/lab/building_2/second_floor/selene_vire ~-6 ~ ~-12
execute as @p at @s positioned ~-6 ~ ~-12 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}

# --- Ancient Crater ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-18 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Ancient Crater","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/high_hide/eddie ~ ~ ~-20
execute as @p at @s positioned ~ ~ ~-20 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/lake/submersible/ajay ~-2 ~ ~-20
execute as @p at @s positioned ~-2 ~ ~-20 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/mid/skeleton_structure/roland ~2 ~ ~-20
execute as @p at @s positioned ~2 ~ ~-20 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/mru/ian ~-4 ~ ~-20
execute as @p at @s positioned ~-4 ~ ~-20 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/mru/kelly ~4 ~ ~-20
execute as @p at @s positioned ~4 ~ ~-20 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/mru/nick ~-6 ~ ~-20
execute as @p at @s positioned ~-6 ~ ~-20 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/mru_field_lead ~6 ~ ~-20
execute as @p at @s positioned ~6 ~ ~-20 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/ancient_crater/upper/archeops_nest/robert ~-8 ~ ~-20
execute as @p at @s positioned ~-8 ~ ~-20 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}

# --- Mystic Highlands ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-26 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Mystic Highlands","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/mystic_highlands/highlands_lab_contact ~ ~ ~-28
execute as @p at @s positioned ~ ~ ~-28 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}

# --- Scorched Mesa ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-34 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Scorched Mesa","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/canyon_observatory/javier ~ ~ ~-36
execute as @p at @s positioned ~ ~ ~-36 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/dam_control_building/jack ~-2 ~ ~-36
execute as @p at @s positioned ~-2 ~ ~-36 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/mine_camp/marston ~2 ~ ~-36
execute as @p at @s positioned ~2 ~ ~-36 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/oil_fields/cleet ~-4 ~ ~-36
execute as @p at @s positioned ~-4 ~ ~-36 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/ranch/kitty ~4 ~ ~-36
execute as @p at @s positioned ~4 ~ ~-36 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/station_contact ~-6 ~ ~-36
execute as @p at @s positioned ~-6 ~ ~-36 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/train/passenger_cab/leopold ~6 ~ ~-36
execute as @p at @s positioned ~6 ~ ~-36 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/train/rear_cab/abigail ~-8 ~ ~-36
execute as @p at @s positioned ~-8 ~ ~-36 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/train_station/arthur ~8 ~ ~-36
execute as @p at @s positioned ~8 ~ ~-36 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/scorched_mesa/train_station/bill ~-10 ~ ~-36
execute as @p at @s positioned ~-10 ~ ~-36 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}

# --- Twilight Keep ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-42 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Twilight Keep","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/armory/dimitar ~ ~ ~-44
execute as @p at @s positioned ~ ~ ~-44 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/church_of_tres/priest_mikhail ~-2 ~ ~-44
execute as @p at @s positioned ~-2 ~ ~-44 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/guard_tower/luka ~2 ~ ~-44
execute as @p at @s positioned ~2 ~ ~-44 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/hotel/charles ~-4 ~ ~-44
execute as @p at @s positioned ~-4 ~ ~-44 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/hotel/milan ~4 ~ ~-44
execute as @p at @s positioned ~4 ~ ~-44 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/nikolai ~-6 ~ ~-44
execute as @p at @s positioned ~-6 ~ ~-44 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/observatory/head_scientist_viktor ~6 ~ ~-44
execute as @p at @s positioned ~6 ~ ~-44 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/sorcery_building/elena ~-8 ~ ~-44
execute as @p at @s positioned ~-8 ~ ~-44 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
execute as @p at @s run npc spawnlinked safari-zone:areas/twilight_keep/storage_building/ivan ~8 ~ ~-44
execute as @p at @s positioned ~8 ~ ~-44 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}

# --- Neon Grove ---
execute as @p at @s run summon minecraft:armor_stand ~ ~2 ~-50 {Invisible:1b,NoGravity:1b,Marker:1b,CustomName:'{"text":"Neon Grove","color":"aqua","bold":true}',CustomNameVisible:1b,Tags:["safari_zone_npc_grid_label"]}
execute as @p at @s run npc spawnlinked safari-zone:areas/neon_grove/medical_center_attendant ~ ~ ~-52
execute as @p at @s positioned ~ ~ ~-52 as @e[type=pixelmon:npc,sort=nearest,limit=1,distance=..2] run data merge entity @s {PersistenceRequired:1b}
