# Auto-generated by scripts/generate_spawn_all_npcs_line.sh
# Source directory: /Users/matthewvogt/Dev/Minecraft Modding/playerspawnfixer-template-1.21.1/run/saves/New World/datapacks/pixelmon_research_example/data/safari-zone/pixelmon/npc/preset/areas
# Run as player: /function safari-zone:debug/spawn_all_npcs_line
# Grid settings: columns=10, front_offset=4, column_spacing=2, row_spacing=4, section_gap=4
# Cardinal aligned grid: no diagonal placement.
# Grouped by location with floating labels.
# Uses player yaw only (pitch ignored) and player height.

# Remove old section labels from previous test runs (near the player).
execute as @p at @s run kill @e[type=minecraft:armor_stand,tag=safari_zone_npc_grid_label,distance=..256]

# South
execute as @p at @s if entity @s[y_rotation=-44.999..44.999] run function safari-zone:debug/spawn_all_npcs_line_south
# West
execute as @p at @s if entity @s[y_rotation=45..134.999] run function safari-zone:debug/spawn_all_npcs_line_west
# East
execute as @p at @s if entity @s[y_rotation=-134.999..-45] run function safari-zone:debug/spawn_all_npcs_line_east
# North (split for wraparound)
execute as @p at @s if entity @s[y_rotation=135..180] run function safari-zone:debug/spawn_all_npcs_line_north
execute as @p at @s if entity @s[y_rotation=-180..-135] run function safari-zone:debug/spawn_all_npcs_line_north
